version: "3.8"

services:
    shopapp:
        build:
            args:
                user: pure
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: shopapp
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www:rw
            - ./docker-compose/logs:/var/log/:rw
            - ./storage/app/public:/var/www/storage/app/public/:rw
            - ./docker-compose/logs/laravel:/var/www/storage/logs/:rw
        networks:
            - shop

    shopdb:
        image: mysql:8.0
        container_name: shopdb
        restart: unless-stopped
        ports:
            - 8001:${DB_PORT}
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./tmp/db:/var/lib/mysql:rw
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - shop
    shopnginx:
        image: nginx:latest
        container_name: shopnginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www:rw
            - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ./storage/app/public:/var/www/public/storage:rw
            - ./docker-compose/certbot/www:/var/www/certbot/:ro
            - ../puresh.ru/docker-compose/certbot/conf/:/etc/nginx/ssl/:ro
            - ./docker-compose/logs/nginx/:/var/log/nginx/:rw
        networks:
            - shop

networks:
    shop:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.221.0/28
